import MANIFEST from '../../../assets/world/muralla/manifest.json';
import background from '../../../assets/world/muralla/background.png';
import bench from '../../../assets/world/muralla/bench.png';
import bin from '../../../assets/world/muralla/bin.png';
import board from '../../../assets/world/muralla/board.png';
import bollard from '../../../assets/world/muralla/bollard.png';
import bollardMarked from '../../../assets/world/muralla/bollardMarked.png';
import gull from '../../../assets/world/muralla/gull.png';
import player from '../../../assets/world/muralla/player.png';
import pot from '../../../assets/world/muralla/pot.png';
import tableSet from '../../../assets/world/muralla/tableSet.png';
import tableSetFolded from '../../../assets/world/muralla/tableSetFolded.png';
import tree from '../../../assets/world/muralla/tree.png';
import waitress from '../../../assets/world/muralla/waitress.png';
import windbreakEast from '../../../assets/world/muralla/windbreakEast.png';
import windbreakSide from '../../../assets/world/muralla/windbreakSide.png';
import windbreakWest from '../../../assets/world/muralla/windbreakWest.png';
import type { Facing } from '../types';

/**
 * World art is committed raster PNG. Some current files can be generated by
 * `tools/art` as placeholders, but approved external/hand-authored assets may
 * replace them without changing the runtime contract. The renderer only blits
 * images: nothing is painted procedurally at load time.
 */
export interface SpriteInfo {
  file: string;
  /** `placeholder` until approved external art replaces the file. */
  status: string;
  width: number;
  height: number;
  frameWidth: number;
  frameHeight: number;
  frames: number;
  rows: number;
  /** Ground contact point inside one frame. */
  anchorX: number;
  anchorY: number;
}

export const SPRITES: Readonly<Record<string, SpriteInfo>> = MANIFEST.sprites;

export const SPRITE_URLS: Readonly<Record<string, string>> = {
  background,
  bench,
  bin,
  board,
  bollard,
  bollardMarked,
  gull,
  player,
  pot,
  tableSet,
  tableSetFolded,
  tree,
  waitress,
  windbreakEast,
  windbreakSide,
  windbreakWest,
};

/** Character sheets: rows = directions, columns = idle + two steps. */
export const CHARACTER_ROWS: Readonly<Record<Facing, number>> = {
  down: 0,
  up: 1,
  right: 2,
  left: 3,
};

export type SpriteImages = ReadonlyMap<string, HTMLImageElement>;

/** Loads every sprite once; resolves when all images are decoded. */
export function loadSpriteImages(
  ids: Iterable<string> = Object.keys(SPRITE_URLS),
): Promise<SpriteImages> {
  const entries = [...new Set(ids)].map(async (id) => {
    const url = SPRITE_URLS[id];
    if (!url) throw new Error(`Unknown sprite: ${id}`);
    const img = new Image();
    img.src = url;
    await img.decode();
    const info = SPRITES[id];
    if (info && (img.naturalWidth !== info.width || img.naturalHeight !== info.height)) {
      throw new Error(
        `Sprite "${id}" decoded as ${img.naturalWidth}×${img.naturalHeight}; manifest expects ${info.width}×${info.height}`,
      );
    }
    return [id, img] as const;
  });
  return Promise.all(entries).then((list) => new Map(list));
}
